# Generated by Django 2.1.1 on 2018-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borehole',
            name='diameter',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='casing',
            name='od_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='kick_off_point',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='parent_depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='parent_track',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='true_vertical_depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tubular',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='well',
            name='api_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
