# Generated by Django 2.1.1 on 2018-09-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_auto_20180922_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perforation',
            name='casing',
        ),
        migrations.AddField(
            model_name='perforation',
            name='penetrates_cement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perforation',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wells.Track'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borehole',
            name='diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casing',
            name='od_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='kick_off_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='parent_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='parent_track',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='true_vertical_depth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
